name: Update Adobe List

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行一次更新操作
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-adobe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Fetch clash.yaml
        run: |
          curl -o clash.yaml https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/clash.yaml

      - name: Create directory for adobe.list
        run: |
          mkdir -p rule/adobe

      - name: Replace and convert clash.yaml to adobe.list format
        run: |
          echo '#规则数量: 1305' > rule/adobe/adobe.list
          echo '#不支持的规则数量: 0' >> rule/adobe/adobe.list
          echo '#已排除的规则数量: 0' >> rule/adobe/adobe.list
          echo -e "\n#-----------------以下为解析后的规则-----------------#" >> rule/adobe/adobe.list
          
          # 使用 sed 进行全文替换，把 - DOMAIN, 替换为 DOMAIN,
          sed 's/^-\sDOMAIN,*/DOMAIN,/' clash.yaml >> rule/adobe/adobe.list

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update adobe list'
          git push