name: Update Adobe List

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo apt-get install -y jq
          # 安装 yq 命令行工具
          wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Fetch clash.yaml
        run: |
          curl -o clash.yaml https://raw.githubusercontent.com/ignaciocastro/a-dove-is-dumb/main/clash.yaml

      - name: Convert clash.yaml to adobe.list format
        run: |
          # 获取 YAML 中的所有域名列表并转换为 adobe.list 格式
          echo '#规则数量: 1305' > adobe/adobe.list
          echo '#不支持的规则数量: 0' >> rule/adobe/adobe.list
          echo '#已排除的规则数量: 0' >> rule/adobe/adobe.list
          echo -e "\n#-----------------以下为解析后的规则-----------------#" >> rule/adobe/adobe.list

          # 提取所有的域名并写入文件
          yq '.domains[]' clash.yaml | sed 's/^/DOMAIN,/' >> rule/adobe/adobe.list

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add adobe/adobe.list
          git commit -m "Update adobe list"
          git push